### ISSUE TITLE
Smart handling of simulation system where one of period or semimajor axis is not available

### ISSUE THREAD

**Issue by SK1Y101** [SK1Y101/TransitProject#1]
**Is your feature request related to a problem? Please describe.**
When instantiating a simulation (ie: kepler-19b), the data supplied contains a semi-major axis for only one planet, but an orbital period for all three. This can cause issues if semi-major axis is selected as a simulation parameter

**Describe the solution you'd like**
The setup should scan for NaN values in sma and per, if any are found, it should look to substitute any values to those not included. This should then be propagated into the simulation possibility space, such that it will only select one or the other as required.

**Describe alternatives you've considered**
Automatically including both semi-major axis and period in every simulation setup.
This would introduce unnecessary computation, though.

**Additional context**
Should introduce minimal additional simulation where possible, as that can be upwards of an hour mistake if implemented incorrectly.

**Comment by skyecas** [comment]
fixed
