### ISSUE TITLE
Investigate accuracy of TTV simulation

### ISSUE THREAD

**Issue by SK1Y101** [SK1Y101/TransitProject#2]
**Describe the bug**
Running a simulation of kepler 19b shows a TTV on the order of a day.

**To Reproduce**
Steps to reproduce the behaviour:
execute python3 simulationPipeline.py --planet kepler19b with orbital period parameter.
wait.
see output too large

**Expected behaviour**
According to literature, this should be on the order of several minutes.

**Screenshots**
None needed, it's my problem

**Additional context**
this highlights something in the code that is very much incorrect. the multi-order of magnitude incorrect implies a line of code is very much wrong.

**Comment by skyecas** [comment]
I believe this has been fixed by manually changing the units in Rebound
